homeassistant:
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config
default_config:


frontend:
  themes: !include_dir_merge_named themes
discovery:
  
logger:
  default: error

recorder:
  db_url: !secret db_url

tts:
  - platform: google_translate

http:

folder_watcher:
  - folder: /config

weather:
  - platform: darksky
    api_key: !secret api_key 
    mode: daily

cover:
  - platform: myq
    username: !secret username
    password: !secret cover_password
  - platform: group
    entities:
      - cover.center_garage_door
      - cover.left_garage_door
      - cover.right_garage_door

lutron_caseta:
  host: 192.168.163.235
  keyfile: /ssl/lutron/caseta.key
  certfile: /ssl/lutron/caseta.crt
  ca_certs: /ssl/lutron/caseta-bridge.crt
  
nest:
  client_id: !secret client_id
  client_secret: !secret client_secret
  project_id: e023daae-3cb1-4b41-b32a-1d104d9cf072
  subscriber_id: projects/hanest-1606958330679/subscriptions/Nest
  

shopping_list:

camera:
  - platform: generic
    still_image_url: !secret still_image_url
    name: !secret name 


notify:
  - name: Home Assistant Notification
    platform: pushbullet
    api_key: !secret api_key2


roomba:
  - host: 192.168.163.113
    blid: A17C3F6CD2A84411BD0774899F2FD251
    password: :1:1606403217:XLWH0MyvtVOOTwxb
  

light: !include light.yaml
media_player: !include media_player.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml 
device_tracker: !include device_tracker.yaml
binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
#cast: !include cast.yaml
cloud: !include cloud.yaml
input_select: !include input_select.yaml


uilogs:

panel_iframe:
  plex:
    title: 'Plex'
    url: 'http://192.168.163.15:32400/web/index.html'
    icon: mdi:plex

spotify:
  client_id: 56c6e2517c654a359c0aa33255a78675
  client_secret: 27b78f3081034a2f84beadfc3b0640ce

google:
  client_id: 1052769629459-rn7nro2bm86mqb95d9qsbh3oddjjm1i3.apps.googleusercontent.com
  client_secret: U3QI5STYh0MeBf3ujqsebHVG

plex_assistant:
  url: 'http://192.168.163.15:32400'
  token: '3uYx2rnueFKykqPaiNAp'
  default_cast: 'Living Room TV'
  language: 'en'
  tts_errors: true

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key